# Generated by Django 5.0.1 on 2024-02-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('CourseName', models.CharField(max_length=250)),
                ('Duration', models.IntegerField(default=0)),
                ('Seat', models.IntegerField(default=0)),
            ],
        ),
    ]
